### ISSUE TITLE
Resolve Merge Issues Caused by Non-English or Special Character Filenames

### ISSUE THREAD

**Issue by Canaan-HS** [PeteJobi/RealEsrganUpscalerGUI#7]
**When processing files with non-English filenames or special symbols, the merge operation in the second stage consistently fails. First, the error message in the UI is too vague, making it difficult to identify the root cause. Additionally, I would like to suggest implementing a filename adaptation feature. For example, the original filename could be temporarily stored in a variable, while a specific English name is used during processing. Then, in the final merge stage, the original name could be restored. This is just my suggestion, and I’m not sure if it’s feasible. I hope you can fix this issue.**

**Comment by PeteJobi** [comment]
Fixed in [v4.1.1](https://github.com/PeteJobi/RealEsrganUpscalerGUI/releases/tag/v4.1.1)

**Comment by Canaan-HS** [comment]
I’m sorry, but based on my testing, the issue has not been successfully fixed. I tested with both Traditional and Simplified Chinese, but it still does not work correctly. I randomly selected two names, "修復測試" and "修复测试", and it seems that this time the problem is related to encoding conversion.

For reference, my environment:
- OS: Windows 11 23H2 Pro for Workstations
- .NET SDK: Versions 6 to 9 installed

---

![Image](https://github.com/user-attachments/assets/32d33f47-1c8d-4385-af84-3081709984ce)

![Image](https://github.com/user-attachments/assets/fa0408ab-95d7-4da0-85f2-d258669aa285)

![Image](https://github.com/user-attachments/assets/3e21b4b1-3357-4457-81bb-cd56b3ce78b4)

**Comment by Canaan-HS** [comment]
If your environment is unable to reproduce this garbled text issue, could it be related to this setting:

![Image](https://github.com/user-attachments/assets/46506f10-747e-4c96-a0cc-9f612f414e0d)

I've attached the link to the video of my actions below. Since it's hosted on a free service, it will only be available for 2 days. Also, since OBS recording cannot handle HDR display, the colors might look off, so please don't mind that.

https://streamable.com/z1g05d

**Comment by PeteJobi** [comment]
I was able to upscale it without problems.

![Image](https://github.com/user-attachments/assets/bfb3ec1b-bdc5-40f0-a9e9-ae164ef92ea8)

![Image](https://github.com/user-attachments/assets/e5e7002e-8435-4b19-b4bf-9207fca5f5d1)

Please send me the logs at _/Documents/RealEsrganUpscalerGUI_

**Comment by PeteJobi** [comment]
Ok. I was able to reproduce by changing the below to Chinese.

![Image](https://github.com/user-attachments/assets/eff5dd3d-6fb0-4f8d-a5fa-4b2476503770)

I will have a fix soon.

**Comment by Canaan-HS** [comment]
Haha, so it really was this issue! Turns out it's a problem caused by Windows.

**Comment by PeteJobi** [comment]
Please retry [v4.1.1](https://github.com/PeteJobi/RealEsrganUpscalerGUI/releases/tag/v4.1.1)

**Comment by Canaan-HS** [comment]
> Please retry [v4.1.1](https://github.com/PeteJobi/RealEsrganUpscalerGUI/releases/tag/v4.1.1)

Thank you for the quick fix and response! I've confirmed that the issue is resolved, and it has greatly improved our user experience. Really appreciate your effort!
